version: '3.0'

networks:
    traefik:
        external: true

services:
    astrochart:
        image: node:carbon
        working_dir: '/home/node/Astrochart'
        command: bash -c "yarn install && yarn run dev"
        volumes:
            # Mount the project directory to the container, so that changes
            # made inside the container reflect on the host.
            - ./:/home/node/Astrochart/
        networks:
          - traefik
        labels:
          - "traefik.backend=astrochart"
          - "traefik.frontend.rule=Host:astrochart.localhost"
          - "traefik.docker.network=traefik"
          - "traefik.enable=true"
          - "traefik.port=8080"
