version: '3.3'
services:
    astrochart:
        build:
            context: .
            args:
                # User Id and Group Id for the local user at the host.
                - UID=1000
                - GID=985
        working_dir: '/home/node/Astrochart'
        command: bash -c "yarn install && bower install && grunt serve"

        ports:
            # From `grunt serve`
            - 9001:9001
        volumes:
            # Mount the project directory to the container, so that changes 
            # made inside the container reflect on the host.
            - ./:/home/node/Astrochart/
